name: Build & Deploy Package to PyPI

on:
  release:
    types: [published]
    branches: 
    - main

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Python Distribution
        run: |
          python3 -m pip install --upgrade build
          cd pip_package
          python3 -m build
          
      - name: Publish Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: pip_package/dist/
